steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pengaduan", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/pengaduan"]
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run",
        "deploy",
        "pengaduan",
        "--image",
        "gcr.io/$PROJECT_ID/pengaduan",
        "--port",
        "4000",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
